# CloudCannon configuration for MALT. website

# Global editable regions configuration
_editables:
  content:
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    horizontalrule: true
    blockquote: true
    removeformat: true
  text:
    bold: true
    italic: true
    link: true

# Paths
paths:
  uploads: images

# Collections
collections_config: {}

# Editor configuration
_inputs: {}
