source: /
paths:
  output: /
  uploads: images
collections_config:
  pages:
    path: ''
    output: true
    url: '/[full_slug]'
    icon: wysiwyg
    glob:
      - '**/*.html'
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    filter:
      exclude:
        - node_modules
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    horizontalrule: true
    image_size_attributes: true
    italic: true
    link: true
    numberedlist: true
    removeformat: true
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    italic: true
    link: true
timezone: Etc/UTC
